apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: daniel
  template:
    metadata:
      labels:
        app: daniel
    spec:
      containers:
        - name: nginx
          image: nginx
